services:
    flickr_twig_extension:
        class: \FlickrTwigExtension
        tags:
            - { name: twig.extension }
        arguments:
            - %sculpin.output_dir%
            - %kernel.cache_dir%
            - 101b16dc5520438f7d99540b792acfe3
            - True

